### PR TITLE
Convert windows-1252 to utf8 encoding

### PR DESCRIPTION
**Pull request by nickbattam-tessella**
Fix encoding errors reported by MLint

### CODE REVIEW

**Review by oerc0122 — APPROVED** [review]
If that's the only one.

**Comment by nickbattam-tessella** [comment]
Looks like that was the only file - there were no errors reported in the PR build

**Comment by hsautessella** [comment]
[Looks like there could be one more.](https://anvil.softeng-support.ac.uk/jenkins/job/PACE-neutrons/job/Herbert/job/PR-Scientific-Linux-7-2018b/623/mlint/info/)

**Review by hsautessella — APPROVED** [review]
No more error messages 👍

**Pull request merged**
